### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Graciela2102** [SistemasTecTlaxiaco/infografia-Graciela2102#1]
![Infrografia-Realidad aumentada](https://user-images.githubusercontent.com/99610866/153770630-633c124b-2cc2-45dd-b224-042ffba6f22d.png)

**Comment by IvanMc98** [comment]
La infografía cuenta con información adecuada, entendible y resumida. Ademas de contar con las referencias bibliograficas. 
calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho..y revisado
